* TODO Add some examples of proofs to show the syntax
* TODO Should we add a way to annotate each inference with additional vampire options?
  Probably not, since the ultimate goal is to have vampire find the complete proof by itself.
* TODO Should we allow some mechanism to pass options with spaces to vampire?
  Currently we simply split the argument string with the function ~words~.
* TODO Write shell script for vampire invocation into =--vampire-output-dir=
  Be sure make it executable.
  Use absolute paths in the scripts.
  It should be possible to easily run vampire for a certain inference.
  Also pass through additional options (would be helpful to add =--show_active on= later).
* TODO Parallelize proof checking
  Add a flag =-n= to set the number of threads, defaulting to the number of (real) CPU cores.
* TODO Change the "--continue-on-error" options to distinguish between timeouts and errors
  We want an option s.t. we can continue on timeout/incomplete strategy,
  but abort on errors.
  Maybe just rename it to "-c"/"--continue-on-timeout"?
* TODO Add option to check if axioms are inconsistent
  Add option "--check-axioms".
  Of course it's not decidable, but it might still help to rule out some mistakes.
* TODO Print =[axiom]= after check mark if it's an axiom
